### ISSUE TITLE
SSL issues on https://dot.net/v1/dotnet-install.sh 

### ISSUE THREAD

**Issue by dave-yotta** [dotnet/install-scripts#161] opened 2021-03-11 10:01 UTC
We get availability issues from time to time that break CI, e.g:

#9 [base  5/19] RUN curl -sSL https://dot.net/v1/dotnet-install.sh > dotnet-install.sh
#9 sha256:cd648a29406a7c31992f71cc1a80253599bbf38404632e8c231709d77b310cec
#9 0.539 curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to dot.net:443 
#9 ERROR: executor failed running [/bin/sh -c curl -sSL https://dot.net/v1/dotnet-install.sh > dotnet-install.sh]: exit code: 35

This was at 11 Mar 2021 at 00:16 GMT

Is there a way to contact the maintainer of this site?  Are there any SLAs etc?

**Comment by bozturkMSFT** [comment] 2021-03-15 17:16
Hi @dave-yotta,
 We have an internal ticket for this, but unfortunately no resolution yet. 
 For the time being, you can try modifying your script to retry in case of a failure. I know it is not a real solution, but it may help stabilize your CI while the actual issue is being fixed.
 cc @ChrisSfanos @MattGal.

**Comment by MattGal** [comment] 2021-03-16 17:45
@dave-yotta my suggestion would just be to check in the script to your repo until this is addressed.  This sort of support ticket can be very challenging to get resolved, and if the script fails to get you the .NET Core version you want you can wait until then to get the updated version.

**Comment by dave-yotta** [comment] 2021-03-17 09:28
The rate of error is probably not high enough to justify maintaining either of these approaches but I'll see what the team thinks.  I would guess it happens once every week or two.  It's not a massive problem if it hits a PR build, but becomes more of a problem when it affects nightly or release for example.  It's too frequent to ignore however.

So I do have a few questions:
 - I'm not 100% sure what SSL_ERROR_SYSCALL exit code 35 means - possibly no supported algorithms available?  
 - Do you have confirmation this is a problem with dot.net, or that it is not?
 - Are there any SLAs for dot.net and if so what are they?

The reason I ask is to formulate a course of action:
 - Problem with dot.net, there is no SLA: implement workaround is the only option
 - Problem with dot.net, there is SLA:  chase owner of SLA to get this fixed within the advertised timeframe
 - Not a problem with dot.net: raise issue with other providers (e.g. base image maintainers, CI service providers etc)

**Comment by oscarmh** [comment] 2021-04-16 08:50
@bozturkMSFT any news ?

**Comment by bozturkMSFT** [comment] 2021-04-29 15:59
@oscarmh Have you been able to escalate this with Azure after our internal communication? Since the issue is not related to the install scripts, we unfortunately cannot provide a fix here.

@dave-yotta I'm sorry, I must have missed your questions. I will try my best to answer in case they are still valid.
- I'm not sure. If it was about missing algorithms though, I would expect it to happen more deterministically.
- There is no confirmation on this, unfortunately. 
- I'm not sure. The proper way to get this information would be to ask https://support.microsoft.com/

**Comment by bekir-ozturk** [comment] 2021-05-31 09:01
I will close this issue on the grounds that it is not actionable for us and it is not an install-script specific issue. Let me know if you think this should be reopened and feel free to continue discussions on this thread.

**Closed by bekir-ozturk** 2021-05-31 09:01 UTC

**Comment by dave-yotta** [comment] 2021-06-21 07:03
@bekir-ozturk can we at least get a stable tag here on github so we don't have to go via dot.net (which is broken, again, I take it back :( )
