### ISSUE TITLE
Error installing .NET Aquisition failed

### ISSUE THREAD

**Issue by manascb1344** [dotnet/install-scripts#385] opened 2023-08-27 13:50 UTC
An error occurred while installing .NET (6.0): .NET Acquisition Failed: Installation failed: Error: Command failed: "/home/mcb76/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.7.1/dist/install scripts/dotnet-install.sh" -InstallDir "/home/mcb76/.vscode-server/data/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/6.0.21" -Version 6.0.21 -Runtime dotnet
bash: /home/mcb76/miniconda3/envs/tftest1/lib/libtinfo.so.6: no version information available (required by bash)
/home/mcb76/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.7.1/dist/install scripts/dotnet-install.sh: line 1253: link_types[$link_index]: unbound variable

this is the issue

tried installing .net again by first doing --purge and again installing triend installing using conda too
then also tried installing from the dotnet documentation
also another error that is seen is polyglot notebooks needs dotnet sdk version 7.0 or higher

I AM RUNNING MY VSCODE FROM A REMMOTE SERVER
I HAVE WSL2 INSTALLED ON TOP OF WINDOWS
VSCODE IS INSTALLED ON WINDOWS 
I HAVE AN ACTIVE CONDA ENVIRONMENT 
I RUN VSCODE FROM WSL TERMINAL USING code .

**Comment by donJoseLuis** [comment] 2023-08-29 07:14
@MichalPavlik , please take a look (following up on our internal thread on this issue)

**Comment by MichalPavlik** [comment] 2023-08-29 07:39
Hello @manascb1344, my understanding is that the installation is happening inside WSL2 environment. I tried to reproduce it by using dotnet-install.sh in Ubuntu 22.04.2 LTS hosted in WSL2:

```
curl -sSL https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh
chmod +x dotnet-install.sh
./dotnet-install.sh -Version 6.0.21 -Runtime dotnet
```

The installation was successful. Could you please tell us what distribution are you using? Could you also please try to install .NET manually using commands I posted here? Thank you.

**Comment by MichalPavlik** [comment] 2023-08-29 09:09
I tired to run `code .` from my WSL terminal. It caused VS Code Server installation. Then I installed C# DevKit extension to check if .NET will be installed. I found runnable .NET in `home/<username>/.vscode-server/data/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.10/dotnet`.

It might be an network issue. @manascb1344, could you please also follow steps described in this comment?
https://github.com/dotnet/vscode-csharp/issues/6004#issuecomment-1664760326

**Comment by manascb1344** [comment] 2023-08-30 18:48
> 

![image](https://github.com/dotnet/install-scripts/assets/122693801/96214eba-3879-401b-a1e5-d9ff581f2c20)

**Comment by YuliiaKovalova** [comment] 2023-08-30 20:43
Hi @manascb1344 ,

It doesn't look like dotnet-install problem, but rather something curl related. 
Could you try to apply some recommendations from this thread?
https://stackoverflow.com/questions/30017397/error-curl-usr-local-lib-libcurl-so-4-no-version-information-available-requ

**Comment by MichalPavlik** [comment] 2023-08-31 14:51
@manascb1344, are you able to try install script without using Conda? We would like to narrow down the root cause, but we are not able to reproduce it.

**Comment by manascb1344** [comment] 2023-08-31 18:22
> @manascb1344, are you able to try "install-script.sh" without using Conda? We would like to narrow down the root cause, but we are not able to reproduce it.
> 
> cc: @baronfel

how shall i try this install-script.sh

**Comment by manascb1344** [comment] 2023-08-31 18:23
> Hi @manascb1344 ,
> 
> It doesn't look like dotnet-install problem, but rather something curl related. Could you try to apply some recommendations from this thread? https://stackoverflow.com/questions/30017397/error-curl-usr-local-lib-libcurl-so-4-no-version-information-available-requ

tried this but got the same error

**Comment by manascb1344** [comment] 2023-08-31 18:23
I always see error acquiring dotnet error on opening vs code

**Comment by YuliiaKovalova** [comment] 2023-09-01 13:59
@manascb1344 , could you also try to run the command
`conda install -c conda-forge ncurses`
and reboot VS Code?

More details can be find here:
https://stackoverflow.com/questions/72103046/libtinfo-so-6-no-version-information-available-message-using-conda-environment

**Comment by YuliiaKovalova** [comment] 2023-09-13 07:00
close as with no response after provided guidance.

**Closed by YuliiaKovalova** 2023-09-13 07:00 UTC
Labels: Iteration:2023September
