### ISSUE TITLE
Same changeset now fails with 2147450735

### ISSUE THREAD

**Issue by matkoch** [dotnet/install-scripts#132] opened 2021-02-01 01:38 UTC
I started getting a `2147450735` exit code from the PowerShell script building the same changeset. On January 17th everything was still working okay. Now the script seems to correctly install the SDK, but returns the non-zero exit code. Unfortunately, I can't verify if the script changed between then and today, I just see some commits from December 17th. So my question here is just if you can confirm whether the publicly accessible script (https://dot.net/v1/dotnet-install.ps1) has changed.

**Comment by bozturkMSFT** [comment] 2021-02-02 11:16
Hi @matkoch,
 Yes, major changes were deployed after January 20th. The change updated the scripts on https://dot.net/:
- from commit https://github.com/dotnet/install-scripts/commit/5be8817c5478df30cc4229e06c9ab87ca1e5f3f1 (deployed shortly after November 10th, 2020.)
- to commit https://github.com/dotnet/install-scripts/commit/b732e7b618adcfc68f769355cd907aec7e6cd028 (deployed shortly after January 20th, 2021).

I haven't been able to reproduce this. What arguments are you passing the script?

**Comment by bozturkMSFT** [comment] 2021-02-08 06:38
Closing since we cannot investigate this without further info.
Feel free to comment with the requested info and I will reopen the issue.

**Closed by bozturkMSFT** 2021-02-08 06:38 UTC
Labels: needs-more-info
