### ISSUE TITLE
dotnet install script treats `-Channel 7.0 -Version latest` as Preview 2

### ISSUE THREAD

**Issue by tannergooding** [dotnet/install-scripts#273] opened 2022-04-28 02:37 UTC
Running `& $DotNetInstallScript -Channel 7.0 -Version latest -InstallDir $DotNetInstallDirectory -Architecture $architecture` currently causes `Preview 2` to install

```
dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.

dotnet-install: Extracting the archive.
dotnet-install: Note that the script does not resolve dependencies during installation.
dotnet-install: To check the list of dependencies, go to https://docs.microsoft.com/dotnet/core/install/windows#dependencies
dotnet-install: Installation finished
C:\Users\tagoo\source\repos\terrafx.interop.vulkan\artifacts\dotnet\sdk\7.0.100-preview.2.22153.17\MSBuild.dll
...
```

Preview 3 has been out for nearly 2 weeks and so the `latest` should have been updated by this point.

**Comment by YuliiaKovalova** [comment] 2022-05-09 07:56
Hi @tannergooding ,

Thank you for reaching us. I have redirected your request to arcade team, because they are responsible for aka.ms links generation.

**Comment by MattGal** [comment] 2022-05-10 00:36
@tannergooding I will synch with @YuliiaKovalova when I can but given the way the script is put together, what's in channel "7.0" right now is preview 5 bits, not 3 or even 4.

You can run `dotnet-install.ps1 -Channel 7.0-preview3 -Quality signed -Version latest` to get the latest preview 3 bits.  I'm not sure what the actual intent is here so I'm not closing or resolving anything, but I'm unsure why "7.0 latest" would point to preview 3 and not daily builds of p5.

**Comment by tannergooding** [comment] 2022-05-10 00:57
@MattGal, I'm merely reporting what the following steps reports:
1. Download https://dot.net/v1/dotnet-install.ps1
2. Run `.\dotnet-install.ps1 -Channel 7.0 -Version latest -InstallDir .\dotnet -Architecture x64`

```
F:\test> $env:DOTNET_CLI_TELEMETRY_OPTOUT = 1
F:\test> $env:DOTNET_MULTILEVEL_LOOKUP = 0
F:\test> $env:DOTNET_SKIP_FIRST_TIME_EXPERIENCE = 0
F:\test> .\dotnet-install.ps1 -Channel 7.0 -Version latest -InstallDir .\dotnet -Architecture x64

Do you want to run software from this untrusted publisher?
File F:\test\dotnet-install.ps1 is published by CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US and is
not trusted on your system. Only run scripts from trusted publishers.
[V] Never run  [D] Do not run  [R] Run once  [A] Always run  [?] Help (default is "D"): R
dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.

dotnet-install: Extracting the archive.
dotnet-install: Adding to current process PATH: "F:\test\dotnet\". Note: This change will not be visible if PowerShell was run as a child process.
dotnet-install: Note that the script does not resolve dependencies during installation.
dotnet-install: To check the list of dependencies, go to https://docs.microsoft.com/dotnet/core/install/windows#dependencies
dotnet-install: Installation finished
F:\test> .\dotnet\dotnet.exe --version
7.0.100-preview.2.22153.17
F:\test> ls .\dotnet\sdk\

    Directory: F:\test\dotnet\sdk

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          2022-05-09    17:49                7.0.100-preview.2.22153.17
```

As you can see. The `dotnet.exe --version` is reported as `7.0.100-preview.2.22153.17` which matches the SDK included in that directory.

This is not only behind the latest public preview, but behind the latest nightly preview as well. As far as I can remember, this has traditionally not been the actual "latest" builds but rather the latest build for a given preview. I've logged and reported other issues with `latest` not being "up to date" in the past.

**Comment by mmitche** [comment] 2022-05-10 20:42
@tannergooding The docs are a bit muddy on this. I **think** it should install nothing though. Without `-Quality`, the default is `ga`. .NET 7 has not GA'd yet. Based on the implementation, you should have to pass `-Quality preview`, which returns .NET 7 Preview 4 as expected. I think the issue is that at some point the GA links got updated.

@rbhanda @bekir-ozturk

**Comment by tannergooding** [comment] 2022-05-10 20:44
That's definitely possible, but its worked this way as far back as I can remember (my source control history shows at least since 3.1).

I'm fine with explicitly updating to `-Quality preview` is that's the "right" thing.

**Comment by mmitche** [comment] 2022-05-10 20:47
I think `preview` is more explicit. Again, it's a bit muddy in the docs. IMO the obvious behavior is that 'ga' is implicitly 'preview' prior to GA of a specific Runtime MAJOR.MINOR or SDK release band. But that does not appear to be how it's implemented right now. I think this should get fixed in either the docs or in the script. Or both.

**Comment by tannergooding** [comment] 2022-05-10 21:03
To me its somewhat beneficial for it to be implicitly `preview` before GA and implicitly `ga` after GA.

It allows less CI changes and to implicitly stay up to date with the latest publicly released bits. Users who don't desire that can always explicitly specify the quality or even the direct version.

So I'd prefer we document that as such and then ensure it works like that moving forward (it's how I thought it was roughly working already).

**Comment by YuliiaKovalova** [comment] 2022-05-11 08:33
Hi,

Thank you for your investigation and offered paths for resolving this issue.
Currently, @bekir-ozturk  and I are discussing the best way for doing this. 
I will return to you once I have more details.

**Comment by baronfel** [comment] 2022-05-13 15:01
What if we changed the default quality for the scripts from `ga` to `latest`? We'd need to clean up the `ga` links for 7.0 (because there is no GA as of yet), but this would allow simple invocations of the script to always resolve to _an_ SDK, and be transparently upgraded from preview to release version as they become available. We'd need to check on the impact of this with users like:

* Github Actions
* Arcade
* Rahul/Lee/etc

but I think this makes sense from a UX perspective, while continuing to allow core complex users of the script to keep a particular quality bar consistent across uses of the scripts.

**Closed** 2022-06-14 14:22 UTC
