### ISSUE TITLE
dotnet/cli   dotnet-install-sh  3.1.100  --runtime variations

### ISSUE THREAD

**Issue by emveepee** [dotnet/install-scripts#28] opened 2020-01-20 14:05 UTC
Using dotnet-install.sh on linux  doesn't give inconsistent versions and I cannot update aspnetcore to current release

dotnet-install.sh -c LTS --runtime aspnetcore -DryRun
dotnet-install: Payload URLs:
dotnet-install: Primary named payload URL: https://dotnetcli.azureedge.net/dotnet/aspnetcore/Runtime/3.1.0/aspnetcore-runtime-3.1.0-linux-x64.tar.gz
dotnet-install: Repeatable invocation: ./dotnet-install.sh --version "3.1.0" --install-dir "/root/.dotnet" --architecture "x64" --runtime "aspnetcore"

dotnet-install.sh -c LTS  -DryRun
dotnet-install: Payload URLs:
dotnet-install: Primary named payload URL: https://dotnetcli.azureedge.net/dotnet/Sdk/3.1.101/dotnet-sdk-3.1.101-linux-x64.tar.gz
dotnet-install: Repeatable invocation: ./dotnet-install.sh --version "3.1.101" --install-dir "/root/.dotnet" --architecture "x64"

dotnet-install.sh -c LTS --runtime dotnet  -DryRun
dotnet-install: Payload URLs:
dotnet-install: Primary named payload URL: https://dotnetcli.azureedge.net/dotnet/Runtime/3.1.1/dotnet-runtime-3.1.1-linux-x64.tar.gz
dotnet-install: Repeatable invocation: ./dotnet-install.sh --version "3.1.1" --install-dir "/root/.dotnet" --architecture "x64" --runtime "dotnet"

/dotnet-install.sh -c 3.1 -runtime aspnetcore -DryRun
dotnet-install: Payload URLs:
dotnet-install: Primary named payload URL: https://dotnetcli.azureedge.net/dotnet/aspnetcore/Runtime/a1388f194c30cb21b36b75982962cb5e35954e4e/aspnetcore-runtime-a1388f194c30cb21b36b75982962cb5e35954e4e-linux-x64.tar.gz
dotnet-install: Repeatable invocation: ./dotnet-install.sh --version "a1388f194c30cb21b36b75982962cb5e35954e4e" --install-dir "/root/.dotnet" --architecture "x64" --runtime "aspnetcore

**Comment by bozturkMSFT** [comment] 2020-11-05 12:40
Hi all,

 The files required to install the SDK or runtimes are stored on a blob storage. Whenever an internal SDK build runs, new versions of the files are published to the storage. There are also `latest.version` files which store what version is the latest in a given channel.

 Occasionally, builds fail at some stage and what is written on a latest.version file do not match what is stored on the blob storage. This is temporary and the issue is usually fixed with the next build that runs to completion. 

 I checked the cases reported above, and the scenarios seem to be working now (except for the PATH issue, which should be unrelated).

 Please let us know if you are still having issues.

Thank you.

**Closed by bozturkMSFT** 2020-11-05 12:40 UTC
Labels: bug, triaged
