### ISSUE TITLE
SH doesn't correctly grab global.json sdk version

### ISSUE THREAD

**Issue by jbobo** [dotnet/install-scripts#7] opened 2020-04-09 19:18 UTC
https://dotnet.microsoft.com/download/dotnet-core/scripts/v1/dotnet-install.sh when run as `bash ./dotnet-install.sh --jsonfile ./global.json` grabs everything in `sdk` after `version` instead of only grabbing the `sdk.version` value.

Example of `global.json`:
```
{
  "sdk": {
    "version": "3.1",
    "allowPrerelease": false,
    "rollForward": "latestPatch"
  }
}
```

error:
```
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/3.1allowPrerelease:falserollForward:latestPatch/dotnet-sdk-3.1allowPrerelease:falserollForward:latestPatch-linux-x64.tar.gz
curl: (22) The requested URL returned error: 404 Not Found
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Sdk/3.1allowPrerelease:falserollForward:latestPatch/dotnet-sdk-3.1allowPrerelease:falserollForward:latestPatch-linux-x64.tar.gz
dotnet-install: Downloading legacy link: https://dotnetcli.azureedge.net/dotnet/Sdk/3.1allowPrerelease:falserollForward:latestPatch/dotnet-dev-centos-x64.3.1allowPrerelease:falserollForward:latestPatch.tar.gz
curl: (22) The requested URL returned error: 404 Not Found
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Sdk/3.1allowPrerelease:falserollForward:latestPatch/dotnet-dev-centos-x64.3.1allowPrerelease:falserollForward:latestPatch.tar.gz
dotnet_install: Error: Could not find/download: `.NET Core SDK` with version = 3.1allowPrerelease:falserollForward:latestPatch
dotnet_install: Error: Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2e484a9-5e0c-eb3e-1413-7b507c4fa07d
* Version Independent ID: 5bc7caa5-f1c2-d7d5-fe02-80c65cca9672
* Content: [dotnet-install scripts - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script)
* Content Source: [docs/core/tools/dotnet-install-script.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-install-script.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by kondratyev-nv** [comment] 2020-08-03 13:28
It looks like the issue can be fixed by removing the line https://github.com/dotnet/install-scripts/blob/master/src/dotnet-install.sh#L471
```
sdk_list="$(echo -e "${sdk_list}" | tr -d '[[:space:]]')"
```
On macOS, echo does not have a `-e` argument, so all lines of key-value pairs in `sdk_list` are merged into a single line. Removing it seems to fix it.

I've already created a PR in sdk repo - https://github.com/dotnet/sdk/pull/12339, as I thought that was the right place to fix it. All tests are passed and I've added more tests to reproduce the issue there. 

I can create a similar PR in the install-scripts repo. However, `./build.sh` from the root of the repo throws and error, and I don't see tests (as in https://github.com/dotnet/sdk/blob/master/src/Tests/InstallationScript.Tests/GivenThatIWantToInstallTheSdkFromAScript.cs) to make sure that changes are working. If anyone can suggest a way to build this repo and test the changes I would be happy to open a PR.

**Comment by AR-May** [comment] 2020-10-23 07:11
Hello @kondratyev-nv!

I agree, it seems the problem is in this line. Your PR from SDK repo should solve it. Do you mind making a similar PR to this repo?

The `GivenThatIWantToInstallTheSdkFromAScript.cs` file was added: see
https://github.com/dotnet/install-scripts/blob/master/tests/Install-Scripts.Test/GivenThatIWantToInstallTheSdkFromAScript.cs.
The easiest way to test the changes as for now, however, is to run automatic tests on the PR. I'd recommend commit and make a PR with the tests, see that they failed, then commit also the bug fix and see the tests pass.

**Comment by kondratyev-nv** [comment] 2020-10-23 14:25
@AR-May Hi! Sure, I'll create one here 🙂

**Comment by AR-May** [comment] 2020-10-27 07:43
@kondratyev-nv Thank you!

**Closed** 2020-10-30 08:17 UTC
Labels: bug, triaged

**Comment by RehanSaeed** [comment] 2020-11-02 16:18
Has the fix for this been released?

**Comment by RehanSaeed** [comment] 2020-11-03 10:21
When I try the latest script I get the following failure when running on Ubuntu:

```
Build started
git clone -q --branch=use-latest-major-dotnet-sdk https://github.com/RehanSaeed/Schema.NET.git /home/appveyor/projects/schema-net
git checkout -qf 0f930f0479cf250ee953515547558ef336a6fc86
Running "build_script" scripts
if ($isWindows) {
  Invoke-WebRequest "https://dot.net/v1/dotnet-install.ps1" -OutFile "./dotnet-install.ps1"
  ./dotnet-install.ps1 -JSonFile global.json -InstallDir 'C:\Program Files\dotnet'
}
else {
  Invoke-WebRequest "https://dot.net/v1/dotnet-install.sh" -OutFile "./dotnet-install.sh"
  sudo chmod u+x dotnet-install.sh
  if ($isMacOS) {
    sudo ./dotnet-install.sh --jsonfile global.json --install-dir '/Users/appveyor/.dotnet'
  } else {
    sudo ./dotnet-install.sh --jsonfile global.json --install-dir '/usr/share/dotnet'
  }
}
dotnet_install: Error: Unable to find the SDK:version node in `global.json`(B
Command exited with code 1
Build failed
```

You can see the build on AppVeyor [here](https://ci.appveyor.com/project/RehanSaeed/schema-net/builds/36095819/job/a0d6w00u99jn11jv).

**Comment by bozturkMSFT** [comment] 2020-11-03 11:41
Hi @RehanSaeed ,

 The change is merged to master, but we haven't deployed it to dot.net website yet. We, unfortunately, don't deploy that frequently unless there is a serious blocking issue, because deploying is a manual process.

 I will get this deployed soon. As a workaround, you can download the scripts using the GitHub link https://raw.githubusercontent.com/dotnet/install-scripts/master/src/dotnet-install.ps1  instead of https://dot.net/v1/dotnet-install.ps1 .

**Comment by RehanSaeed** [comment] 2020-11-03 21:36
Thanks @bozturkMSFT. So you don't ship with .NET 5, it's just ad-hoc right? In that case, is there a way to know when it's released? Or can you keep us posted about when it goes out?

**Comment by bozturkMSFT** [comment] 2020-11-05 15:08
Hi @RehanSaeed . No, we don't follow .NET shipping schedule. I have created a PR here https://github.com/dotnet/website/pull/2418 . It usually takes 1 day to a week to get it released after that. There is, unfortunately, no way of knowing unless you check the internal release build. I will notify you here once it is available on the website.

**Comment by bozturkMSFT** [comment] 2020-11-10 12:48
Hi @RehanSaeed ,
 Changes are now available at https://dot.net/v1/dotnet-install.sh
