### ISSUE TITLE
Consume version metadata files to ensure picking up the right build from each channel

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/install-scripts#65] opened 2020-08-04 23:40 UTC
See https://github.com/dotnet/aspnetcore/issues/16859 and https://github.com/dotnet/runtime/issues/3833 for the details.

**Comment by bozturkMSFT** [comment] 2020-11-23 16:47
Duplicate of the fixed issue https://github.com/dotnet/install-scripts/issues/85.
Closing.

**Closed by bozturkMSFT** 2020-11-23 16:47 UTC
Labels: maintenance-mode-prerequisite, triaged
