### ISSUE TITLE
How to get latest sdk 7.0.2xx build

### ISSUE THREAD

**Issue by erdembayar** [dotnet/install-scripts#338] opened 2022-11-28 19:05 UTC
Hi.
I tried `./dotnet-install --channel 7.0.2xx`, but following errors. I want to test my changes from https://github.com/dotnet/sdk/pull/29017

```
'7.0.2xx' is not a supported value for -Quality option. Supported values are: daily, signed, validated, preview, ga.
If you think this is a bug, report it at https://github.com/dotnet/install-scripts/issues.
At C:\Users\xxxx\dotnet-install.ps1:270 char:19
+ ...   default { throw "'$Quality' is not a supported value for -Quality o ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: ('7.0.2xx' is no...scripts/issues.:String) [], RuntimeException
    + FullyQualifiedErrorId : '7.0.2xx' is not a supported value for -Quality option. Supported values are: daily, sig
   ned, validated, preview, ga. If you think this is a bug, report it at https://github.com/dotnet/install-scripts/is
  sues.
```

```
 ./dotnet-install -Channel 7.0.2xx -Quality preview -InstallDir C:\cli
dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.

dotnet-install: Failed to locate the latest version in the channel '7.0.2xx' with 'preview' quality for 'dotnet-sdk', os: 'win', architecture: 'x64'.
dotnet-install: Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support.
aka.ms link resolution failure
At C:\Users\xxxxx\dotnet-install.ps1:1012 char:13
+             throw "aka.ms link resolution failure"
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (aka.ms link resolution failure:String) [], RuntimeException
    + FullyQualifiedErrorId : aka.ms link resolution failure
```

**Comment by marcpopMSFT** [comment] 2022-11-30 22:49
Moving to the install-scripts repo. The installers themselves are on the main installer page as a download.

**Comment by MichalPavlik** [comment] 2023-02-09 10:19
This looks like duplicate of #337

**Closed** 2023-02-09 16:20 UTC
