### ISSUE TITLE
Linux install script shouldn't point to the .dotnet data folder

### ISSUE THREAD

**Issue by adegeo** [dotnet/install-scripts#158] opened 2021-03-01 23:47 UTC
There has been some feedback given to the docs about issues installing .NET on Linux. dotnet/docs#23035

Looking at some information, it seems that the scripts are possibly installing dotnet into the hidden `~/.dotnet` folder, which it probably shouldn't. I believe this folder is used for the global tools and package resolution (among other things).

Here are the paths used when you install via the package manager on Ubuntu:

| item | path |
| --- | --- |
|dotnet command |  `/usr/bin/dotnet` |
|dotnet install folder | `/usr/share/dotnet/` |
|dotnet data folder | `$HOME/.dotnet/` |

I think the bash script should install to `/usr/share/dotnet/` (or some env variable that points to `/user/share/` ?? I'm not familiar enough with linux) or at least point to something other than `.dotnet` such as `$HOME/dotnet/` (notice I removed the period)

The [manual instructions](https://docs.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#manual-install) (I'm the author of the article) do in fact point to `$HOME/dotnet` and I took those off the download site as the information was migrated to docs.

**Comment by bozturkMSFT** [comment] 2021-03-02 09:04
Hi @adegeo,
 Thank you for the issue. I agree that it would be ideal to have all the installers install into the same directory so that users would know where to look. However, only admins have write permission to `/usr/bin/` and `/usr/share/` folders. Not requiring admin rights is one of the hard requirements of install scripts. So it looks like those two options are out.

 We can switch to `$HOME/dotnet`, but it won't unify the install location across installers. It will also break people that are running the script and then relying on bits being at `$HOME/.dotnet`. So I'm not a 100% sure if the change will be worth it. Can you help me understand why `$HOME/.dotnet` is a bad choice? I understand that there are other stuff under `$HOME/.dotnet`, but do we know (or expect) any problems caused by this?

@KathleenDollard Any thoughts on this?

**Comment by adegeo** [comment] 2021-03-03 01:09
Ehh yeah changing the default now seems bad as it could break things for a lot of people. The only way I see around that is a new url that old scripts and automation wouldn't be using.

Is `.dotnet` a bad choice? I'm not sure. I know that `.` folders are generally ignored and excluded from things, so I wouldn't think you want to hide .NET away from the user.

**Comment by oliversturm** [comment] 2021-03-03 09:10
I think you should consider using `~/.local/share` for this purpose.

**Comment by bozturkMSFT** [comment] 2021-03-08 10:35
Considering that the scripts are in maintenance mode and the issue is not a high-impact/blocking issue, I will close this for the time being.

**Closed by bozturkMSFT** 2021-03-08 10:35 UTC
