### ISSUE TITLE
Channel 8.0 installing old version

### ISSUE THREAD

**Issue by IvanJosipovic** [dotnet/install-scripts#378] opened 2023-08-11 02:49 UTC
When running ```dotnet-install.ps1 -Channel 8.0```, it installs .Net 8 Preview 6 instead of Preview 7.

Seems the issue is with, https://dotnetcli.azureedge.net/dotnet/Sdk/8.0/latest.version

.Net 8 Preview 7 was released 2 days ago, https://github.com/dotnet/sdk/releases/tag/v8.0.100-preview.7.23376.5

**Comment by baronfel** [comment] 2023-08-11 02:51
@AR-May can you take a look at the release automation that pushes builds to these buckets tomorrow?

**Comment by IvanJosipovic** [comment] 2023-08-11 03:00
One thing I noticed is that depending on the location, the script works, so it may be a CDN cache that needs the purged.

**Comment by donJoseLuis** [comment] 2023-08-11 15:39
Greetings,
A local test showed the expected bits in blob storage.

`.\dotnet-install.ps1 -Channel 8.0 -dryrun`
dotnet-install: Payload URLs:
dotnet-install: URL #0 - primary: https://dotnetcli.azureedge.net/dotnet/Sdk/8.0.100-preview.7.23376.3/dotnet-sdk-8.0.100-preview.7.23376.3-win-x64.zip
dotnet-install: URL #1 - legacy: https://dotnetcli.azureedge.net/dotnet/Sdk/8.0.100-preview.7.23376.3/dotnet-dev-win-x64.8.0.100-preview.7.23376.3.zip

The folks that maintain the processes that place bits on blob storage also confirmed the bits are there.

For sure this is not a problem with the install-scripts, because of that I'll close the issue.

@IvanJosipovic are you still experiencing the problem?
If so, can you please share a network trace to understand where the problem is?  A should likely be tracked by the entity that owns the network node causing the problem.

**Closed by donJoseLuis** 2023-08-11 15:39 UTC
Labels: missing-binaries

**Comment by IvanJosipovic** [comment] 2023-08-11 15:44
Hey,

The issue resolved itself last night after I reported the issue.

9:58pm PDT
![image](https://github.com/dotnet/install-scripts/assets/9521987/95bfd626-a14d-4851-a55b-03fe065b5223)

10:00pm PDT
![image](https://github.com/dotnet/install-scripts/assets/9521987/4bc9a87c-3a88-43c2-8cf6-0bc4031f9583)

**Comment by IvanJosipovic** [comment] 2023-08-11 15:53
Hey, sorry I spoke to soon.

I can repro the issue with Github Actions right now.

See pipeline, https://github.com/IvanJosipovic/dotnetinstall/blob/main/.github/workflows/cicd.yaml

![image](https://github.com/dotnet/install-scripts/assets/9521987/0ccbeb4a-6818-4df6-bea8-e9dff99159c0)

**Comment by donJoseLuis** [comment] 2023-08-25 06:29
Greetings @IvanJosipovic I just now noticed your comments after the issue was closed.

The best way to trouble shoot the issue would be to have a network trace when it reproduces. I agree with your conclusion that the culprit is in the network layer. A trace will specifically identify that.
