### ISSUE TITLE
Path assembly bug in dotnet-install.ps1

### ISSUE THREAD

**Issue by InteXX** [dotnet/install-scripts#496] opened 2024-07-22 11:02 UTC
On line 770, `$InstallRoot` is set to the value of the `DOTNET_INSTALL_DIR` environment variable (`C:\Program Files\dotnet\sdk` in my case). This results in the creation of a duplicate `sdk` folder name in the `Is-Dotnet-Package-Installed()` function at line 789.

`$DotnetPackagePath` is incorrectly set to `C:\Program Files\dotnet\sdk\sdk\8.0.303`.

This results in the script attempting to proceed with the installation instead of failing gracefully (at line 1234), which in turn results in an inappropriate error:
```
dotnet-install: Failed to extract package. Exception: Exception calling "ExtractToFile" with "3" argument(s): "Access to the path 'C:\Program Files\dotnet\sdk\dotnet.exe' is denied."
Exception calling "ExtractToFile" with "3" argument(s): "Access to the path 'C:\Program Files\dotnet\sdk\dotnet.exe' is denied."
At E:\Users\Work\Downloads\dotnet-install.ps1:864 char:21
+ ...             [System.IO.Compression.ZipFileExtensions]::ExtractToFile( ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnauthorizedAccessException
```
I'm running the script non-elevated and with no parameters.

**Comment by GangWang01** [comment] 2024-08-23 09:48
I could reproduce the exception: `Exception calling "ExtractToFile" with "3" argument(s): "Access to the path 'C:\Program Files\dotnet\sdk\dotnet.exe' is denied."` when running the script non-elevated. This is expected due to default security settings of the folder `C:\Program Files` that normal user just has read & execute permission, no write permission. Extracting the package to the install root `C:\Program Files\dotnet\sdk\sdk` would write files there but lacked write permission. Then the access was denied.
Running as administrator didn't have this exception and the dotnet was installed successfully or it told the dotnet version is already installed.

Regarding the duplicate `sdk` folder name in the path `C:\Program Files\dotnet\sdk\sdk\8.0.303`, it's because specified `DOTNET_INSTALL_DIR` environment variable(`C:\Program Files\dotnet\sdk`) is the directory where `dotnet.exe` will be installed. The relative path `\sdk` to the directory is where SDK package 8.0.303 will be located and then its full path has duplicate `sdk` folder name. To void this, you need to change `DOTNET_INSTALL_DIR` environment variable to be `C:\Program Files\dotnet`.

**Comment by InteXX** [comment] 2024-08-24 19:17
@GangWang01 

> it's not a bug

Actually, I still believe it is. Two separate bugs, that is.

The script should test for any current value in `DOTNET_INSTALL_DIR` and respond appropriately, as well as check/prompt for elevation before writing to a protected location.

**Comment by InteXX** [comment] 2024-08-24 19:19
@GangWang01, @YuliiaKovalova 

> it's not a bug

Actually, I still believe it is. Two separate bugs, that is.

The script should test for any current value in `DOTNET_INSTALL_DIR` and respond appropriately, as well as check/prompt for elevation before writing to a protected location.

That's what I would do, anyway, were I the author.

**Comment by YuliiaKovalova** [comment] 2024-09-23 14:56
the ticket was resolved in scope of : https://github.com/dotnet/install-scripts/pull/513

Thank you for reporting it!

**Closed by YuliiaKovalova** 2024-09-23 14:56 UTC
Labels: bug, Priority:2
