### ISSUE TITLE
Cannot download for master branch latest version

### ISSUE THREAD

**Issue by heng-liu** [dotnet/install-scripts#50] opened 2020-06-26 02:38 UTC
Failed to download latest version from master branch:
```
C:\work\testinstall> .\dotnet-install.ps1 -Channel master -Version latest -Architecture x64 -i "C:\work\testinstall"
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100-preview.7.20325.10/dotnet-sdk-5.0.100-preview.7.20325.10-win-x64.zip
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100-preview.7.20325.10/dotnet-sdk-5.0.100-preview.7.20325.10-win-x64.zip
dotnet-install: Downloading legacy link: https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100-preview.7.20325.10/dotnet-dev-win-x64.5.0.100-preview.7.20325.10.zip
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100-preview.7.20325.10/dotnet-dev-win-x64.5.0.100-preview.7.20325.10.zip
```

**Comment by bozturkMSFT** [comment] 2020-06-29 14:40
The issue is not with the scripts. The problem is that the SDK build process fails to put the correct artifacts into correct place.

Related issue in the installer repo is here: https://github.com/dotnet/installer/issues/7893
Closing this one.

**Closed by bozturkMSFT** 2020-06-29 14:40 UTC
Labels: triaged
